# Generated by Django 2.2.4 on 2019-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190828_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pasword',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
