# Generated by Django 2.2.4 on 2019-08-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_pasword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pasword',
            new_name='password',
        ),
    ]
