# Generated by Django 2.2.4 on 2019-08-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190829_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.FloatField(),
        ),
    ]
