# Generated by Django 3.0.2 on 2020-01-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_od_death',
            new_name='date_of_death',
        ),
    ]
